### ISSUE TITLE
Question: Does this support Flux LED aswell?

### ISSUE THREAD

**Issue by henryruhs** [namacha/python-magichue#32]
I wonder if "Flux LED" just a rebranding of the "MagicLight"? There is this [flux_led](https://github.com/Danielhiversen/flux_led) library that uses the same type of ssdp discovery.

## magichue

https://github.com/namacha/python-magichue/blob/master/magichue/discover.py#L13-L14

## flux_led

https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__main__.py#L1210
https://github.com/Danielhiversen/flux_led/blob/master/flux_led/__main__.py#L1216

**Comment by namacha** [comment]
I think yes. Basically this library should work with flux-LEDs, there may be slight differences though.

**Comment by henryruhs** [comment]
Thanks for the quick response, I close that issue and suggest to extend the README with that information.
