### ISSUE TITLE
Support for candle mode after firmware update

### ISSUE THREAD

**Issue by maverage** [namacha/python-magichue#37]
Magichue currently does not support candle mode, which was added in the latest firmware update for magic home controllers.

Reproduce the behavior:
Set one magic hue device to candle mode in app
```python
magichue.Light(ip)
```
fails with ```KeyError: 95```
**Device**
 - Magic Home Controller RGB + IR with BLE

**Comment by namacha** [comment]
Please try update python-magichue to the latest version.  I fixed that bug at 0.2.9.3.
