### ISSUE TITLE
Bug: SyntaxError upon importation

### ISSUE THREAD

**Issue by ThomasJones4** [namacha/python-magichue#5]
`File "B:\Python\python-magichue-0.1\magichue\test1.py", line 2, in <module>
    import magichue
  File "B:\Python\python-magichue-0.1\magichue\magichue.py", line 210
    self._status = Status(*rgb, self.w, self.is_white, self.on)
SyntaxError: only named arguments may follow *expression`

**Comment by namacha** [comment]
Thank you for reporting bug!
It seems that you are using python2.  I fixed this issue, but I recommend you to use python3.  Anyway I would be happy if you try this library again.
