### ISSUE TITLE
Unable to connect to IP

### ISSUE THREAD

**Issue by colinhartigan** [namacha/python-magichue#8]
**Describe the bug**
I inserted my IP into the example code and ran it which yielded the error:
"ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it"

**To Reproduce**
Code to reproduce the behavior:
```python
import time
import magichue


light = magichue.Light('my ip')
if not light.on:
    light.on = True

if not light.is_white:
  light.is_white = True

light.rgb = (255, 255, 255)

for hue in range(1000):
    print("running")
    light.hue = hue / 1000
    time.sleep(0.05)
```

**Device**
 Nexlux LED strip (connected to MagicHome)

**Comment by namacha** [comment]
I wonder if your bulb uses default port(5577/tcp).

You can use nmap, tcpscan, telnet, etc. to scan available ports.

**Comment by colinhartigan** [comment]
I had to adjust some settings within my router and it worked.
