### ISSUE TITLE
Feature Request: set speed of modes

### ISSUE THREAD

**Issue by colinhartigan** [namacha/python-magichue#9]
One of my favorite features of the Magic Home app is the ability to adjust the speed of the mode. The default speed is very fast and I would like to be able to control this speed within my project.

**Comment by namacha** [comment]
Now you can adjust the speed by

```python
light.speed = 1  # 100%

light.speed = 0.3  # 30%
```

**Comment by colinhartigan** [comment]
I've tried to uninstall/reinstall and upgrade the package but I keep getting
``
AttributeError: 'Light' object has no attribute 'speed'
``

**Comment by namacha** [comment]
Oh sorry, I haven’t uploaded package to PyPI yet. 
 If you want to try it now, you need to execute `git clone https://github.com/namacha/python-magichue && cd python-magichue && python setup.py` (you may have to uninstall magichue library before run setup.py)

**Comment by namacha** [comment]
Upload to PyPI done.  you can do `pip --upgrade install python-magichue`
